package gui;

import Metodos_mysql.Metodos_sql;
import javax.swing.JOptionPane;

/**
 *
 * @author mirym
 */
public class Iniciar_Sesion extends javax.swing.JFrame {

    /**
     * Creates new form Iniciar_Sesion
     */
    public Iniciar_Sesion() {
        initComponents();
        //Esta parte del codigo nos pondra la ventana en el medio cuando abre;
        setLocationRelativeTo(null);
    }

     Metodos_sql metodos = new Metodos_sql() ;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblIniciar_Sesion = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnRegresar = new javax.swing.JButton();
        btnIniciar_sesion = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtContraseña = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        lblCafe = new javax.swing.JLabel();
        lblFondo_Iniciar_Sesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciar_Sesion.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblIniciar_Sesion.setText("INICIAR SESIÓN");
        jPanel2.add(lblIniciar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 40));

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContraseña.setText("CONTRASEÑA:");
        jPanel2.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUsuario.setText("USUARIO:");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 340, 10));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setBorder(null);
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 340, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 340, 20));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cerrar-sesion64px.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btnIniciar_sesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIniciar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iniciar-sesion64.png"))); // NOI18N
        btnIniciar_sesion.setText("Iniciar Sesión");
        btnIniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar_sesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnIniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));
        jPanel2.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 182, 340, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 610, 340));

        jPanel3.setBackground(new java.awt.Color(102, 255, 51));

        lblCafe.setBackground(new java.awt.Color(102, 255, 51));
        lblCafe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCafe.setText("Gestor De Planta De Café");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 300, 40));

        lblFondo_Iniciar_Sesion.setBackground(new java.awt.Color(51, 255, 51));
        lblFondo_Iniciar_Sesion.setForeground(new java.awt.Color(102, 255, 51));
        lblFondo_Iniciar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Fondo Login.jpg"))); // NOI18N
        jPanel1.add(lblFondo_Iniciar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      Menu_Inicio ventana = new Menu_Inicio();
      ventana.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar_sesionActionPerformed
     String busqueda_usuario = metodos.buscarUsuarioRegistrado(txtUsuario.getText(), new String(txtContraseña.getPassword()));

        if (txtUsuario.getText().equals("root") && new String(txtContraseña.getPassword()).equals("root")) {
            JOptionPane.showMessageDialog(this, "Iniciaste sesión como root (Administrador)");
            Menu_2 ventana = new Menu_2();
            ventana.setVisible(true);
            this.dispose();
        } else if (busqueda_usuario.equals("Usuario encontrado")) {
            String busqueda_nombre = metodos.buscarNombre(txtUsuario.getText());
            JOptionPane.showMessageDialog(this, "Bienvenida (a) \n" + busqueda_nombre);
            Menu_2 ventana = new Menu_2();
            ventana.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no registrado. Favor registrarse.");
        }
    }//GEN-LAST:event_btnIniciar_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar_sesion;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCafe;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblFondo_Iniciar_Sesion;
    private javax.swing.JLabel lblIniciar_Sesion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables


}