/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author mirym
 */
public class Menu_2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu_2
     */
    public Menu_2() {
        initComponents();
         initComponents();
        //Esta parte del codigo nos pondra la ventana en el medio cuando abre;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegrsae = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        lblMenu_Fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegrsae.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegrsae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cerrar-sesion 32px.png"))); // NOI18N
        btnRegrsae.setText("Regrsar");
        btnRegrsae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegrsaeActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegrsae, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 60));

        btnReporte.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/informe.png"))); // NOI18N
        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 140, 60));

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/insertar.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, 60));

        btnInventario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventario.png"))); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 160, 60));

        lblMenu_Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Menu_Fondo 2 (1).jpg"))); // NOI18N
        jPanel1.add(lblMenu_Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegrsaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegrsaeActionPerformed
      Menu_Inicio ventana = new Menu_Inicio();
      ventana.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnRegrsaeActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // Crear la instancia de la ventana de inserción
        gestionarInventario ventana = new gestionarInventario();
        ventana.setVisible(true);

        // Cerrar la ventana actual
        this.dispose();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
          // Crear la instancia de la ventana de inserción
        reporte ventana = new reporte();
        ventana.setVisible(true);

        // Cerrar la ventana actual
        this.dispose();
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
         // Crear la instancia de la ventana de inserción
    ventanaPrincipal ventana = new ventanaPrincipal();
    ventana.setVisible(true);

    // Cerrar la ventana actual
    this.dispose();
    }//GEN-LAST:event_btnInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnRegrsae;
    private javax.swing.JButton btnReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMenu_Fondo2;
    // End of variables declaration//GEN-END:variables
}
