package gui;

import Metodos_mysql.Metodos_sql;
import javax.swing.JOptionPane;

/**
 *
 * @author mirym
 */
public class Registrar_Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Registrar_Usuarios
     */
    public Registrar_Usuarios() {
        initComponents();
        //Esta parte del codigo nos pondra la ventana en el medio cuando abre;
        setLocationRelativeTo(null);
    }

    Metodos_sql metodos = new Metodos_sql();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecha_Nacimiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumero_Telefonico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnGuardar_registro = new javax.swing.JButton();
        btnRegresar_registro1 = new javax.swing.JButton();
        lblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        lblFondo_Registrar_Usuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Apellido:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 150, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Fecha De Nacimiento:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtFecha_Nacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFecha_Nacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecha_NacimientoActionPerformed(evt);
            }
        });
        jPanel2.add(txtFecha_Nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Cedula o DNI:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Número Telefonico:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtNumero_Telefonico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtNumero_Telefonico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 140, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Correo Electrónico:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 150, -1));

        btnGuardar_registro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardar_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/guardar 64px.png"))); // NOI18N
        btnGuardar_registro.setText("Guardar");
        btnGuardar_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar_registroActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        btnRegresar_registro1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar_registro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cerrar-sesion64px.png"))); // NOI18N
        btnRegresar_registro1.setText("Regresar");
        btnRegresar_registro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar_registro1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar_registro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContraseña.setText("Contraseña:");
        jPanel2.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 100, -1));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 150, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario.setText("Usuario:");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));
        jPanel2.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 680, 410));

        jTextField1.setBackground(new java.awt.Color(102, 255, 102));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField1.setText("Registro De Usuarios");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 260, -1));

        lblFondo_Registrar_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Fondo Registro Usuario (1).jpg"))); // NOI18N
        jPanel1.add(lblFondo_Registrar_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      private void limpiarCampos() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtFecha_Nacimiento.setText("");
        txtCedula.setText("");
        txtNumero_Telefonico.setText("");
        txtCorreo.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtNombre.requestFocus();
    }
  
    private void btnGuardar_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar_registroActionPerformed

        int i = metodos.guardar(txtNombre.getText(), txtApellido.getText(), txtFecha_Nacimiento.getText(), txtCedula.getText(), txtNumero_Telefonico.getText(), txtCorreo.getText(), txtUsuario.getText(), txtContraseña.getText());

        if (i > 0) {
            JOptionPane.showMessageDialog(this, "Datos Registrados Exitosamente.");
            limpiarCampos(); // Limpiar los campos después de guardar
        } else {
            JOptionPane.showMessageDialog(this, "Error No Se Pudo Guardar Los Datos.");
        }
    }//GEN-LAST:event_btnGuardar_registroActionPerformed

    private void btnRegresar_registro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar_registro1ActionPerformed
        Menu_Inicio ventana = new Menu_Inicio();
        ventana.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRegresar_registro1ActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtFecha_NacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecha_NacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecha_NacimientoActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar_registro;
    private javax.swing.JButton btnRegresar_registro1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblFondo_Registrar_Usuario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFecha_Nacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero_Telefonico;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
